
name: Build OpenWrt

on:
  workflow_dispatch:
  push:
    branches:
      - release

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-22.03
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  DOCKER_BUILD_SH: build.sh

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        ARCH: x86_64
        CI_JOB_NAME: deploy-rootfs_x86-64 
        VERSION: 22.03.3
        DOCKER_IMAGE: ansj
      run: |
        bash docker-rootfs.sh
        TARGET=$(echo "$CI_JOB_NAME" | cut -d _ -f 2-)
        VERSION=${VERSION:-snapshot}"
        TARGET=$(echo "$CI_JOB_NAME" | cut -d _ -f 2-)
        VERSION="${VERSION:-snapshot}"
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker tag "ansj/openwrt-x86:$TARGET-$VERSION-R${{ env.DATE_YMD }}" "$DOCKER_IMAGE:rootfs-$TARGET-$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID"
        docker push "ansj/openwrt-x86:$TARGET-$VERSION-R${{ env.DATE_YMD }}"

        
